### ISSUE TITLE
Synchronizacja danych z baza GISu.

### ISSUE THREAD

**Issue by mitorski** [ProteGO-app/backend#38]
Czesc,

zostawie wam tu mala notke na prosbe czlonkow zespolu z ktorym pracowalem nad prawie tym samym tematem. Ciut nas wyprzedziliscie wiec zamykamy temat, z ta jedna roznica ze..

Rozwazcie synchronizacje z danymi GISu ktory identyfikuje zarazonych na podstawie numeru telefonu. Mechanizm juz jest bo korzysta z niego Aplikacja Kwarantanna domowa.

Majac informacje na urzadzeniu o tym ze dany pacjent jest chory bedziecie w stanie policzyc i powiedziec innym uzytkownikom ze mogli byc narazeni na kontakt z chorym, oraz pomoc GISowi w sledzeniu epidemii co defakto chcielismy my zrobic. 

Chetnie odpowiem na pytania jesli sie takowe pojawia i bedzie wola dzialan z waszej strony bo dosc mocno juz rozkminilismy temat jak to powinno dzialac.

Pozdrawiam

**Comment by mpelc87** [comment]
Myślę że wspomniana wyżej synchronizacja z GIS jest KLUCZOWA dla przyszłości tej aplikacji. 
Wg mnie nie ma co liczyć na, wspomnianą na stronie ministerstwa cyfryzacji, "społeczną solidarność i odpowiedzialność".
Znajdzie się napewno sporo osób które będą zakłamywać prawdziwe dane. Np trole którzy dla fanu będą zgłaszać fakt zarażenia i tworzyć fałszywe alarmy. 
Jeżeli użytkownicy będą mieć podejrzenia że dane w aplikacji nie są wiarygodne to albo zlekceważą powiadomienia albo odinstalują taką aplikację. (sam bym tak zrobił, nie będę się kwarantannować myśląc ze podejrzenie zarażenia moze być czyimś żartem)
Tak samo osoby które dostaną pozytywny wynik mogą w stresie najzwyczajniej zapomniec zaklikać tego w aplikacji. 
Mogą również np na prośbę rodziny lub znajomych (z którymi mają osobisty kontakt) nie klikać tego bo: "weź kliknij jutro nie dziś bo muszę załatwić pare spraw na mieście i nie mam czasu na kwarantanne".

Fakt zarażenia przez użytkownika powinien być automatycznie zgłaszany przez system.

Przy takiej integracji rozumiem ze baza danych GIS dostałaby wcześniej dane zarażonych wraz z numerami telefonu.
Wtedy backend proteGo przy pullowaniu informacji z GISu mógłby automatycznie emitować powiadomienia do urządzeń niezależnie od decyzji użytkowników.

Rozważyłbym dodatkowo stałe wysyłanie danych o napotkanych urządzeniach na serwer.
Zeby potem nie było sytuacji że aplikacja zarażonego użytkownika zostanie odinstalowana zanim wyśle swoje dane.

**Comment by mitorski** [comment]
Dokladnie tak to mielismy zaplanowane do realizacji i czekalismy do poniedzialku przed kontaktem z ministerstwem zeby miec jaki kolwiek prototyp aplikacji ale tutaj chlopaki nas wyprzedzili.

Wymieniony problem smieszkow ktorzy by dla beki klikali w aplikacji ze sa chorzy rozwiazalismy wlasnie pomyslem integracji z systemami GISu bo oni i tak te dane maja, a majac historie lokalizacji uzytkownikow bez problemu mozna wytypowac osoby narazone na kontakt z osoba ktora dostala pozytywny wynik testu. To powinno chociaz w teorii pomoc w redukcji transmisji jesli Kowalski dostalby powiadomienie na telefon - mogles byc w kontakcie z chorym, zostales objety kwarantanna.

**Comment by mpelc87** [comment]
pytanie czy proteGo bedzie też tak działać... bo w opisie na stronie ministerstwa nie było o tym mowy
