### ISSUE TITLE
Endpoint confirm_registration zwraca HTTP500 na środowisku deweloperskim

### ISSUE THREAD

**Issue by michalcichon** [ProteGO-app/backend#40]
Request:
```
:method: POST
:scheme: https
:path: /confirm_registration
:authority: europe-west3-anna-dev-272212.cloudfunctions.net
accept: */*
content-type: application/json
accept-encoding: gzip, deflate, br
user-agent: ProteGO%20Dev/1 CFNetwork/1121.2.1 Darwin/18.7.0
content-length: 177
accept-language: en-us

{
	"appVersion": "1.0",
	"lang": "en",
	"code": "SYYAN",
	"registration_id": "6c870d3f82a8f33d0b1ab0c1fd0a8d09",
	"osVersion": "13.3",
	"deviceType": "iPhone 8",
	"platform": "ios",
	"apiVersion": "1"
}
```

Response:
```
:status: 500
x-cloud-trace-context: bcd60228726dd4b472df3091e188a597;o=1
date: Fri, 03 Apr 2020 14:03:51 GMT
content-type: text/html; charset=UTF-8
server: Google Frontend
content-length: 323
alt-svc: quic=":443"; ma=2592000; v="46,43",h3-Q050=":443"; ma=2592000,h3-Q049=":443"; ma=2592000,h3-Q048=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,h3-T050=":443"; ma=2592000


<html><head>
<meta http-equiv="content-type" content="text/html;charset=utf-8">
<title>500 Server Error</title>
</head>
<body text=#000000 bgcolor=#ffffff>
<h1>Error: Server Error</h1>
<h2>The server encountered an error and could not complete your request.<p>Please try again in 30 seconds.</h2>
<h2></h2>
</body></html>
```

**Comment by AlexF0rtune** [comment]
A na swoim postawionym?

**Comment by michalcichon** [comment]
Nie uruchamiałem backendu lokalnie. Sprawdziłem tylko jak aplikacja iOS działa z backendem ustawionym jako środowisko DEV i wszystko działa (łącznie z tym, że dostaję po drodze SMS z kodem) aż do momentu w którym wysyłam dane rejestracyjne na `POST confirm_registration`. Tutaj dostaję 500.

**Comment by jakublipinski** [comment]
Skąd wziąłeś ten endpoint `anna-dev`? Jest nieaktualny. Prawidłowy jest [tutaj](https://github.com/ProteGO-app/specs/blob/master/specs/app_versions.md#dev---%C5%9Brodowisko-rozwojowe)

**Comment by AlexF0rtune** [comment]
@jakublipinski ten endpoint jest obecnie w konfiguracji gradleowego builda na Androidzie - pobrałem repo z trzy godziny temu i moja aplikacja łączy się do https://europe-west3-anna-dev-272212.cloudfunctions.net/

**Comment by michalcichon** [comment]
Tak, środowiska były niedawno zmieniane. W kliencie iOS zmiany weszły dopiero godzinę temu z tym pull requestem: https://github.com/ProteGO-app/ios/pull/40

**Comment by michalcichon** [comment]
Myślę, że to można zamknąć.

**Comment by jakublipinski** [comment]
Dzięki za czujność. Zamykam
