### ISSUE TITLE
Rejestracja: Nieprawidłowe kodowanie znaków w SMS

### ISSUE THREAD

**Issue by michalcichon** [ProteGO-app/backend#41]
"Twój kod" wyświetla się nieprawidłowo.

![image](https://user-images.githubusercontent.com/4848662/78383454-b3e90500-75d8-11ea-87fb-81b98b1b9de6.png)

**Comment by rtpm** [comment]
Można albo bawić się w kodowanie, albo użyć parametru "normalize=1" przy wysyłaniu SMS z klienta SMSAPI.

send_results = client.sms.send(to=msisdn, message=message, normalize=1) który zamieni znaki z ogonkami na odpowiedniki ascii.
