### ISSUE TITLE
Nieprawidłowa interpretacja wartości nagłówka X-Forwarded-For

### ISSUE THREAD

**Issue by bartekn** [ProteGO-app/backend#49]
Według [dokumentacji](https://cloud.google.com/appengine/docs/flexible/python/reference/request-headers) Google Cloud:
> `X-Forwarded-For: [CLIENT_IP(s)], [global forwarding rule IP]`
> A comma-delimited list of IP addresses through which the client request has been routed. The first IP in this list is generally the IP of the client that created the request. The subsequent IPs provide information about proxy servers that also handled the request before it reached the application server. For example:
> ```
> X-Forwarded-For: clientIp, proxy1Ip, proxy2Ip
> ```

Oznacza to, że wartość `X-Forwarded-For` może być w niektórych przypadkach listą adresów IP. Wygląda na to, że można w łatwy sposób oszukać poniższy kod:

https://github.com/ProteGO-app/backend/blob/ce9a500aefacc180e3a90134fa8e82fc8c72b399/functions/register/main.py#L89-L92

ponieważ z reguły serwery doklejają adres IP jeśli klient wyśle ten nagłówek (nie testowałem na Google Cloud).

**Comment by jakublipinski** [comment]
Dzięki. Mega ważne spostrzeżenie. Sprawdzaliśmy wprawdzie w bazie i okazuje się, że zapisują się pojedyncze adresy `ip` ale lepiej dodać sprawdzenie czy jest lista i wziąć pierwszą wartość.

**Comment by skorejwo** [comment]
Jesli obecnie w bazie są pojedyncze adresy - musicie wziąc ostatnią cześć - nie pierwszą. Tyko ostatni wpis jest faktycznym adresem IP klienta.

**Comment by jakublipinski** [comment]
@skorejwo dokumentacja mówi:

> `X-Forwarded-For: [CLIENT_IP(s)], [global forwarding rule IP]`
> A comma-delimited list of IP addresses through which the client request has been routed. The first IP in this list is generally the IP of the client that created the request. The subsequent IPs provide information about proxy servers that also handled the request before it reached the application server. For example:
> 
> `X-Forwarded-For: clientIp, proxy1Ip, proxy2Ip`
> 

Nas interesuje `CLIENT_IP` a nie żadne proxy. Czyli pierwszy element, nie ostatni. Czegoś nie rozumiem?

**Comment by jakublipinski** [comment]
Pogrzebałem jeszcze trochę. Dokładna struktura tego nagłówka jest taka:
`X-Forwarded-For: <unverified IP(s)>, <immediate client IP>, <global forwarding rule external IP>, <proxies running in Google Cloud>` [(źródło)](https://cloud.google.com/load-balancing/docs/https#forwarding_rules_and_addresses)

Czyli najpierw jest to co przesłał (podspoofował) klient. Potem IP klienta. Potem ew. proxy. Ponieważ nie mamy żadnych GCP proxy to naszym IP jest ostatnie IP. 

Jak dodamy jakieś proxy wtedy trzeba będzie je usuwać od prawej strony identyfikując IP należące do Google.

Aktualnie branie ostatniego IP jest poprawnym podejściem.

**Comment by skorejwo** [comment]
> Aktualnie branie ostatniego IP jest poprawnym podejściem.

Dokładnie tak. Trzeba o tym pamietać przy zmianie topologii sieciowej.
