### ISSUE TITLE
Poprawienie weryfikacji IP clienta

### ISSUE THREAD

**Issue by skorejwo** [ProteGO-app/backend#54]
Podczas rejestracji i zapewne nie tylko adres klienta pobierany jest tak:
    ip = request.headers.get('X-Forwarded-For')

Jest to nieprawidłowe, gdyż, gdy w zapytaniu występuje już nagłowek X-Forwarded-For z jakakolwiek wartoscia np fake_ip - proxy googlowe po drodze doda kolejny adres do tego nagłóowka. Bedzie on wygladal tak:
fake_ip, client_ip
Wtedy wzięcie całego stringa do porównania spowoduje, że trywialnie łatwo bedzie można spoofować ten nagłowek - bez wysiłku zmiany prawdziwego adresu IP.
Jesli w naglowku jest lista adresow - trzeba brac ostatni (jeśli podczas testow w naglowku dostawaliscie jeden IP).

DOC: https://cloud.google.com/load-balancing/docs/https , https://tools.ietf.org/html/rfc7239

**Comment by jakublipinski** [comment]
Dzięki. Mamy to już tutaj: https://github.com/ProteGO-app/backend/issues/49
