### ISSUE TITLE
Rate limiting wszystkich API

### ISSUE THREAD

**Issue by jakublipinski** [ProteGO-app/backend#65]
Ze względu na to, że numer telefonu będzie opcjonalny (https://github.com/ProteGO-app/specs/issues/34#issuecomment-609993832) a co za tym idzie będzie można  swobodnie generować `user_id`, potrzebujemy zrobić `rate-limiting` na wszystkie API. Należy go też użyć przy [zabezpieczeniu naszej rejestracji SMS](https://github.com/ProteGO-app/backend/blob/master/sms_registration.md`).

Inspiracje:
https://cloud.google.com/community/tutorials/cloud-functions-rate-limiting
https://pypi.org/project/ratelimit/

Zapraszam do dyskusji.

**Comment by jakublipinski** [comment]
Zwracał na to uwagę @bartekn (https://github.com/ProteGO-app/backend/issues/53#issuecomment-609042954) i @rtpm (https://github.com/ProteGO-app/backend/issues/53#issuecomment-609029150). Dzięki

**Comment by rafbara** [comment]
Czy nie lepiej jest zrobić jakiegos fingerprinta z aplikacji frontendowych do backendu aby całkowicie odciąć niepożądane żądania do backendu ?

**Comment by rafbara** [comment]
> Ze względu na to, że numer telefonu będzie opcjonalny ([ProteGO-app/specs#34 (comment)](https://github.com/ProteGO-app/specs/issues/34#issuecomment-609993832)) a co za tym idzie będzie można swobodnie generować `user_id`, potrzebujemy zrobić `rate-limiting` na wszystkie API. Należy go też użyć przy [zabezpieczeniu naszej rejestracji SMS](https://github.com/ProteGO-app/backend/blob/master/sms_registration.md%60).
> 
> Inspiracje:
> https://cloud.google.com/community/tutorials/cloud-functions-rate-limiting
> https://pypi.org/project/ratelimit/
> 
> Zapraszam do dyskusji.

Jeżeli limitowanie requestów nie jest idetyfikowane np. przez adres ip to zablokuje instalacje aplikacji np. dla 1k użytkowników w ciągu 15 min.
Stanowić to będzie duże ogranicznie w zakładaniu kont - spowoduje duże problemu przy uruchomieniu.

Proszę o komentarze.

**Comment by rtpm** [comment]
@rafbara dlaczego uważasz ze ratelimit na IP zablokuje tak dużo użytkowników ?

Jeśli coś działa na API to raczej ciężko opierać się tylko na mechanizmach obronnych lokalnie na urządzeniu klienta czy to telefon, czy jakieś inne urządzenie (przeglądarka, sesja). Niektóre przeglądarki wkrótce mogą już blokować fingerprinting albo utrudniać. W Chrome już chyba o tym myślą jako mechanizm ochrony prywatności. Co lokalne wg. mnie jest łatwo manipulowalne / łatwe do skopiowania. 

Zmierzając do wniosku. Ochrona na poziomie samego API musi być niezależnie od ochrony zastosowanej na poziomie klienta. Od ochrony przed nadużyciem ilości zapytań po autoryzację i autentyfikację.

**Comment by rafbara** [comment]
> @rafbara dlaczego uważasz ze ratelimit na IP zablokuje tak dużo użytkowników ?
> 
> Jeśli coś działa na API to raczej ciężko opierać się tylko na mechanizmach obronnych lokalnie na urządzeniu klienta czy to telefon, czy jakieś inne urządzenie (przeglądarka, sesja). Niektóre przeglądarki wkrótce mogą już blokować fingerprinting albo utrudniać. W Chrome już chyba o tym myślą jako mechanizm ochrony prywatności. Co lokalne wg. mnie jest łatwo manipulowalne / łatwe do skopiowania.
> 
> Zmierzając do wniosku. Ochrona na poziomie samego API musi być niezależnie od ochrony zastosowanej na poziomie klienta. Od ochrony przed nadużyciem ilości zapytań po autoryzację i autentyfikację.

Chodziło mi o fingerprint aplikacji frontendowych (nie klienta uruchamiające je), w projekcie mamy 2 apki na androida ios i to je chciałem authentykować do backendu API. (Myślałem o wygenerowaniu jakiegoś hasha bcryptem i wysyłaniu go do API z każdej apki mobilnej) Czy poza nimi będą jescze jakieś autoryzowane wejścia do API ?
Jeżeli chodzi o limitowanie requestów to podałem tylko przykład, moim zdaniem każdy request który zostanie "odcięty" to 1 instalacja mniej i jest to półśrodek - nie jest to idealne rozwiązanie.
Konfigurowałem limity na nginx i wiem że trzeba z tym uważać ponieważ można odciąć użytkowników od funkcjonalności aplikacji.

**Comment by jakublipinski** [comment]
Jedyne sposoby weryfikacji czy z backendem komunikuje się aplikacja musiałby być oparte o rozwiązanie opisane tutaj: https://github.com/ProteGO-app/specs/blob/master/specs/security.md#serwer-w-%C5%BCaden-spos%C3%B3b-nie-weryfikuje-czy-rozmawia-z-nim-aplikacja-czy-mo%C5%BCe-kto%C5%9B-si%C4%99-pod-ni%C4%85-podszywa

Będziemy to sprawdzać w dalszych pracach nad aplikacją.
