### ISSUE TITLE
/get_status pozwala na utworzenie wielu beacon_id na daną godzinę

### ISSUE THREAD

**Issue by jasisz** [ProteGO-app/backend#75]
Klient wysyłając odpowiednio spreparowane `last_beacon_date` jest w stanie zmusić system do utworzenia mu wielu identyfikatorów na daną godziną.

**Comment by jakublipinski** [comment]
Dzięki. Wiemy o tym. Na serwerze najpewniej nie będziemy weryfikować czy do spotkania dwóch urządzeń doszło dokładnie w czasie w którym dany `beacon_id` miał się rozgłaszać. Porównanie `beacon_id`s wystarcza aby stwierdzić, że do "spotkania" doszło.
